apiVersion: v2
appVersion: v2.11.7
description: A Helm chart for Argo Workflows
name: argo
version: 0.14.0
icon: https://raw.githubusercontent.com/argoproj/argo/master/docs/assets/argo.png
home: https://github.com/xakraz/charts-1
