name: Lint and publish charts

on:
  pull_request:
    paths:
      - charts/**/*
  push:
    paths:
      - .github/workflows/charts.yml
      - charts/**/*
      - scripts/build-repo.sh
jobs:
  helm-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: Download Helm
        run: |
          curl -L https://get.helm.sh/helm-v3.4.1-linux-amd64.tar.gz | tar -xzf - --strip-component=1 linux-amd64/helm
          chmod +x helm

      - name: Lint using helm
        run: |
          ./helm lint charts/*
